version: "3"
services:
  mongodb:
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=public_gov
    volumes:
      - ./local/data:/data/db
      - ./local/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
